name: macOS
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  raku:
    strategy:
      matrix:
        os:
          - macos-latest
        raku-version:
          - 'latest'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: Raku/setup-raku@v1
        with:
          raku-version: ${{ matrix.raku-version }}
      - name: Install native deps
        run: |
          wget https://github.com/duckdb/duckdb/releases/download/v1.0.0/libduckdb-osx-universal.zip
          unzip libduckdb-osx-universal.zip
          # Ensure the library is in the current directory
          ls -la libduckdb.dylib
          # Set proper permissions
          chmod +x libduckdb.dylib
          # Verify the file exists and get its absolute path
          pwd
          ls -la $(pwd)/libduckdb.dylib
      - name: Install Dependencies
        run: |
          export DYLD_LIBRARY_PATH="$(pwd):$DYLD_LIBRARY_PATH"
          zef install --deps-only .
      - name: Run Tests
        run: |
          export DYLD_LIBRARY_PATH="$(pwd):$DYLD_LIBRARY_PATH"
          raku ./make -v test